language: php

php:
  - 7.0

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install --dev --no-interaction

script:
  - phpunit --coverage-text --coverage-clover=./build/coverage.clover Tests/

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar  -O build/ocular.phar
  - php ./build/ocular.phar code-coverage:upload --format=php-clover ./build/coverage.clover